const mongoose = require('mongoose');

const LoriSchema = new mongoose.Schema({
    lori_lgea: { type: String, required: true },
    lori_school_name: { type: String, required: true },
    lori_location: { type: String, required: true },
    lori_school_code: { type: String, required: true },
    lori_teacher_name: { type: String, required: true },
    lori_trcn_no: { type: String, required: true },
    lori_teacher_gender: { type: String, required: true },
    lori_teacher_phone: { type: String, required: true },
    lori_pupils_female: { type: Number, required: true },
    lori_pupils_male: { type: Number, required: true },
    lori_pupils_total: { type: Number },
    lori_teacher_class_observed: { type: String, required: true },
    lori_lesson_start_time: { type: String, required: true },
    lori_lesson_end_time: { type: String, required: true },
    lori_subject_observed: { type: String, required: true },
    lori_years_experience: { type: Number, required: true },
    lori_observation_date: { type: Date, required: true },
    lori_term: { type: String, required: true },
    lori_age: { type: String, required: true },
    lori_qualification: { type: String, required: true },
    lori_b_1: String,
    lori_b_1_avg: String,
    lori_b_1_desc: String,
    lori_b_2: String,
    lori_b_2_avg: String,
    lori_b_2_desc: String,
    lori_b_3: String,
    lori_b_3_avg: String,
    lori_b_3_desc: String,
    lori_b_4: String,
    lori_b_4_avg: String,
    lori_b_4_desc: String,
    lori_b_5: String,
    lori_b_5_avg: String,
    lori_b_5_desc: String,
    lori_b_6: String,
    lori_b_6_avg: String,
    lori_b_6_desc: String,
    lori_b_7: String,
    lori_b_7_avg: String,
    lori_b_7_desc: String,
    lori_c_went_well_1: String,
    lori_c_went_well_2: String,
    lori_c_could_be_different_1: String,
    lori_c_could_be_different_2: String,
    lori_c_support_needed: String,
    lori_c_teacher_name: String,
    lori_c_teacher_signature: String,
    lori_c_teacher_date: Date,
    lori_c_observer_name_2: String,
    lori_c_observer_designation: String,
    lori_c_observer_phone: String,
    lori_c_observer_date: Date
});

module.exports = mongoose.model('Lori', LoriSchema);
