const mongoose = require('mongoose');

const Silat13Schema = new mongoose.Schema({
    silnat_a_ht_name: { type: String, required: true },
    silnat_a_ht_contact: { type: String, required: true },
    gender_1_3: { type: String, required: true },
    marital_status_1_3: { type: String, required: true },
    highest_qualification_1_3: { type: String, required: true },
    highest_qualification_other_1_3: { type: String },
    leadership_experience_1_3: { type: String, required: true },
    silat13_lgea: { type: String, required: true },
    silat13_school_name: { type: String, required: true },
    silat13_address: { type: String, required: true },
    silat13_location: { type: String, required: true },
    silat13_vocation_type: { type: String, required: true },
    silat13_instructors_male: { type: Number, required: true },
    silat13_instructors_female: { type: Number, required: true },
    silat13_instructors_total: { type: Number },
    silat13_qualified_teachers_male: { type: Number, required: true },
    silat13_qualified_teachers_female: { type: Number, required: true },
    silat13_qualified_teachers_total: { type: Number },
    silat13_non_teaching_male: { type: Number, required: true },
    silat13_non_teaching_female: { type: Number, required: true },
    silat13_non_teaching_total: { type: Number },
    silat13_schools_supported: { type: Number, required: true },
    silat13_avg_distance: { type: Number, required: true },
    silat13_learners_male: { type: Number, required: true },
    silat13_learners_female: { type: Number, required: true },
    silat13_learners_total: { type: Number },
    silat13_instructor_pupil_ratio: { type: String, required: true },
    silat13_additional_staff: { type: Number, required: true },
    discipline_a_1_2: String,
    discipline_b_1_2: String,
    discipline_c_1_2: String,
    discipline_d_1_2: String,
    discipline_e_1_2: String,
    cooperation_a_1_2: String,
    cooperation_b_1_2: String,
    cooperation_c_1_2: String,
    cooperation_d_1_2: String,
    communication_a_1_2: String,
    communication_b_1_2: String,
    communication_c_1_2: String,
    community_a_1_2: String,
    community_b_1_2: String,
    community_c_1_2: String,
    community_d_1_2: String,
    community_e_1_2: String,
    supervision_a_1_2: String,
    supervision_b_1_2: String,
    supervision_c_1_2: String,
    supervision_d_1_2: String,
    records_a_1_2: String,
    records_b_1_2: String,
    records_c_1_2: String,
    records_d_1_2: String,
    records_e_1_2: String,
    health_a_1_2: String,
    health_b_1_2: String,
    health_c_1_2: String,
    health_d_1_2: String,
    health_e_1_2: String,
    signboard: String,
    teachers_furniture_available: Number,
    teachers_furniture_good: Number,
    teachers_furniture_required: Number,
    learners_furniture_available: Number,
    learners_furniture_good: Number,
    learners_furniture_required: Number,
    classroom_available: Number,
    classroom_good: Number,
    classroom_minor_repair: Number,
    classroom_major_repair: Number,
    classroom_required: Number,
    classroom_repair_description: String,
    shared_facility: String,
    shared_facility_schools: String,
    perimeter_fence: String,
    fence_condition: String,
    fence_repair_description: String,
    school_perimeter: String,
    toilet_type: String,
    toilet_cubicle_available: Number,
    toilet_minor_repair: Number,
    toilet_major_repair: Number,
    toilet_renovation_required: Number,
    toilet_additional_required: Number,
    toilet_repair_description: String,
    septic_tank: String,
    water_source: String,
    water_recommendations: String,
    electricity_source: [String],
    electricity_additional_info: String,
    waterlogged: String,
    equipment: [{
        name: String,
        available: Number,
        required: Number
    }],
    photos: [String]
});

module.exports = mongoose.model('Silat_1_3', Silat13Schema);
