const mongoose = require('mongoose');

const Silat14Schema = new mongoose.Schema({
    gender_1_4: { type: String, required: true },
    marital_status_1_4: { type: String, required: true },
    highest_qualification_1_4: { type: String, required: true },
    highest_qualification_other_1_4: { type: String },
    leadership_experience_1_4: { type: String, required: true },
    lgea_name_1_4: { type: String, required: true },
    lgea_address_1_4: { type: String, required: true },
    location_1_4: { type: String, required: true },
    staff_male_1_4: { type: Number, required: true },
    staff_female_1_4: { type: Number, required: true },
    staff_total_1_4: { type: Number },
    teachers_male_1_4: { type: Number, required: true },
    teachers_female_1_4: { type: Number, required: true },
    teachers_total_1_4: { type: Number },
    non_teaching_male_1_4: { type: Number, required: true },
    non_teaching_female_1_4: { type: Number, required: true },
    non_teaching_total_1_4: { type: Number },
    discipline_a_1_4: String,
    discipline_b_1_4: String,
    discipline_c_1_4: String,
    discipline_d_1_4: String,
    discipline_e_1_4: String,
    cooperation_a_1_4: String,
    cooperation_b_1_4: String,
    cooperation_c_1_4: String,
    cooperation_d_1_4: String,
    communication_a_1_4: String,
    communication_b_1_4: String,
    communication_c_1_4: String,
    community_a_1_4: String,
    community_b_1_4: String,
    community_c_1_4: String,
    community_d_1_4: String,
    community_e_1_4: String,
    supervision_a_1_4: String,
    supervision_b_1_4: String,
    supervision_c_1_4: String,
    supervision_d_1_4: String,
    records_a_1_4: String,
    records_b_1_4: String,
    records_c_1_4: String,
    records_d_1_4: String,
    records_e_1_4: String,
    health_a_1_4: String,
    health_b_1_4: String,
    health_c_1_4: String,
    health_d_1_4: String,
    health_e_1_4: String,
    signboard_1_4: String,
    structure_condition_1_4: String,
    offices_good_condition_1_4: Number,
    offices_minor_repairs_1_4: Number,
    offices_major_repairs_1_4: Number,
    offices_renovation_required_1_4: Number,
    offices_additional_required_1_4: Number,
    repair_description_1_4: String,
    staff_furniture_available_1_4: Number,
    staff_furniture_good_condition_1_4: Number,
    staff_furniture_required_1_4: Number,
    offices_available_1_4: Number,
    offices_good_condition_2_1_4: Number,
    offices_minor_repair_1_4: Number,
    offices_major_repair_1_4: Number,
    offices_additional_required_2_1_4: Number,
    repair_description_2_1_4: String,
    shared_facility_1_4: String,
    shared_facility_schools_1_4: String,
    perimeter_fence_1_4: String,
    fence_condition_1_4: String,
    fence_repair_description_1_4: String,
    lgea_perimeter_1_4: String,
    toilet_type_1_4: String,
    toilet_cubicle_available_1_4: Number,
    toilet_minor_repair_1_4: Number,
    toilet_major_repair_1_4: Number,
    toilet_renovation_required_1_4: Number,
    toilet_additional_required_1_4: Number,
    toilet_repair_description_1_4: String,
    septic_tank_1_4: String,
    water_source_1_4: String,
    water_recommendations_1_4: String,
    electricity_source_1_4: [String],
    electricity_additional_info_1_4: String,
    monitoring_vehicles_1_4: String,
    monitoring_vehicles_needed_1_4: Number,
    waterlogged_1_4: String,
    equipment: [{
        name: String,
        available: Number,
        required: Number
    }],
    photos: [String]
});

module.exports = mongoose.model('Silat_1_4', Silat14Schema);
