const mongoose = require('mongoose');

const Silat12Schema = new mongoose.Schema({
    silnat_a_ht_name: { type: String, required: true },
    silnat_a_ht_contact: { type: String, required: true },
    gender_1_2: { type: String, required: true },
    marital_status_1_2: { type: String, required: true },
    highest_qualification_1_2: { type: String, required: true },
    highest_qualification_other_1_2: { type: String },
    leadership_experience_1_2: { type: String, required: true },
    silnat_a_institution_type: { type: String, required: true },
    silat_1_2_localGov: { type: String, required: true },
    silat_1_2_schoolName: { type: String, required: true },
    silat_1_2_address: { type: String, required: true },
    silat_1_2_location: { type: String, required: true },
    silat_1_2_lgea: { type: String, required: true },
    silat_1_2_assembly_start: { type: String },
    silat_1_2_assembly_end: { type: String },
    silat_1_2_teachers_male: { type: Number, required: true },
    silat_1_2_teachers_female: { type: Number, required: true },
    silat_1_2_teachers_total: { type: Number },
    silat_1_2_spec_ed_teachers_male: { type: Number, required: true },
    silat_1_2_spec_ed_teachers_female: { type: Number, required: true },
    silat_1_2_spec_ed_teachers_total: { type: Number },
    silat_1_2_non_teaching_male: { type: Number, required: true },
    silat_1_2_non_teaching_female: { type: Number, required: true },
    silat_1_2_non_teaching_total: { type: Number },
    silat_1_2_learners_male: { type: Number, required: true },
    silat_1_2_learners_female: { type: Number, required: true },
    silat_1_2_learners_total: { type: Number },
    silat_1_2_special_learners: [String],
    silat_1_2_teacher_pupil_ratio: { type: String, required: true },
    silat_1_2_additional_staff_required: { type: Number, required: true },
    silat_1_2_multigrade_classes: { type: Number, required: true },
    silat_1_2_multigrade_reasons: [String],
    discipline_a_1_2: String,
    discipline_b_1_2: String,
    discipline_c_1_2: String,
    discipline_d_1_2: String,
    discipline_e_1_2: String,
    cooperation_a_1_2: String,
    cooperation_b_1_2: String,
    cooperation_c_1_2: String,
    cooperation_d_1_2: String,
    communication_a_1_2: String,
    communication_b_1_2: String,
    communication_c_1_2: String,
    community_a_1_2: String,
    community_b_1_2: String,
    community_c_1_2: String,
    community_d_1_2: String,
    community_e_1_2: String,
    supervision_a_1_2: String,
    supervision_b_1_2: String,
    supervision_c_1_2: String,
    supervision_d_1_2: String,
    records_a_1_2: String,
    records_b_1_2: String,
    records_c_1_2: String,
    records_d_1_2: String,
    records_e_1_2: String,
    health_a_1_2: String,
    health_b_1_2: String,
    health_c_1_2: String,
    health_d_1_2: String,
    health_e_1_2: String,
    signboard: String,
    teachers_furniture_available: Number,
    teachers_furniture_good: Number,
    teachers_furniture_required: Number,
    eccde_furniture_available: Number,
    eccde_furniture_good: Number,
    eccde_furniture_required: Number,
    primary_furniture_available: Number,
    primary_furniture_good: Number,
    primary_furniture_required: Number,
    classroom_available: Number,
    classroom_good: Number,
    classroom_minor_repair: Number,
    classroom_major_repair: Number,
    classroom_required: Number,
    classroom_repair_description: String,
    shared_facility: String,
    shared_facility_schools: String,
    perimeter_fence: String,
    fence_condition: String,
    fence_repair_description: String,
    school_perimeter: String,
    toilet_type: String,
    toilet_cubicle_available: Number,
    toilet_minor_repair: Number,
    toilet_major_repair: Number,
    toilet_renovation_required: Number,
    toilet_additional_required: Number,
    toilet_repair_description: String,
    septic_tank: String,
    water_source: String,
    water_recommendations: String,
    electricity_source: [String],
    electricity_additional_info: String,
    waterlogged: String,
    Important_Special_School_Facilities_Info: String,
    photos: [String]
});

module.exports = mongoose.model('Silat_1_2', Silat12Schema);
