const mongoose = require('mongoose');

const SilnatSchema = new mongoose.Schema({
    silnat_a_institution_type: { type: String, required: true },
    silnat_a_ht_name: { type: String },
    silnat_a_ht_contact: { type: String },
    silnat_a_ht_gender: { type: String },
    silnat_a_ht_marital_status: { type: String },
    silnat_a_ht_highest_qualification: { type: String },
    silnat_a_ht_highest_qualification_other: { type: String },
    silnat_a_ht_years_experience: { type: String },
    silnat_a_es_name: { type: String },
    silnat_a_es_contact: { type: String },
    silnat_a_es_gender: { type: String },
    silnat_a_es_marital_status: { type: String },
    silnat_a_es_highest_qualification: { type: String },
    silnat_a_es_highest_qualification_other: { type: String },
    silnat_a_es_years_experience: { type: String },
    localGov: { type: String, required: true },
    schoolName: { type: String, required: true },
    schoolAddress: { type: String, required: true },
    silnat_location_common: { type: String, required: true },
    latitude: { type: Number },
    longitude: { type: Number },
    silnat_assemblyDevotion_startTime: { type: String, required: true },
    silnat_assemblyDevotion_endTime: { type: String, required: true },
    silnat_teachers_male: { type: Number, required: true },
    silnat_teachers_female: { type: Number, required: true },
    silnat_teachers_total: { type: Number },
    silnat_non_teaching_male: { type: Number, required: true },
    silnat_non_teaching_female: { type: Number, required: true },
    silnat_non_teaching_total: { type: Number },
    silnat_pupils_eccde_male: { type: Number, required: true },
    silnat_pupils_eccde_female: { type: Number, required: true },
    silnat_pupils_eccde_total: { type: Number },
    silnat_pupils_primary_male: { type: Number, required: true },
    silnat_pupils_primary_female: { type: Number, required: true },
    silnat_pupils_primary_total: { type: Number },
    silnat_pupils_special_male: { type: Number, required: true },
    silnat_pupils_special_female: { type: Number, required: true },
    silnat_pupils_special_total: { type: Number },
    silnat_pupils_male: { type: Number, required: true },
    silnat_pupils_female: { type: Number, required: true },
    silnat_pupils_total: { type: Number },
    silnat_teacher_pupil_ratio: { type: Number, required: true },
    silat_1_2_additional_staff_required: { type: Number, required: true },
    silnat_multigrade_classes: { type: Number, required: true },
    silnat_multigrade_reasons: [String],
    discipline_a_1_2: String,
    discipline_b_1_2: String,
    discipline_c_1_2: String,
    discipline_d_1_2: String,
    discipline_e_1_2: String,
    cooperation_a_1_2: String,
    cooperation_b_1_2: String,
    cooperation_c_1_2: String,
    cooperation_d_1_2: String,
    communication_a_1_2: String,
    communication_b_1_2: String,
    communication_c_1_2: String,
    community_a_1_2: String,
    community_b_1_2: String,
    community_c_1_2: String,
    community_d_1_2: String,
    community_e_1_2: String,
    supervision_a_1_2: String,
    supervision_b_1_2: String,
    supervision_c_1_2: String,
    supervision_d_1_2: String,
    records_a_1_2: String,
    records_b_1_2: String,
    records_c_1_2: String,
    records_d_1_2: String,
    records_e_1_2: String,
    health_a_1_2: String,
    health_b_1_2: String,
    health_c_1_2: String,
    health_d_1_2: String,
    health_e_1_2: String,
    signboard: String,
    teachers_furniture_available: Number,
    teachers_furniture_good: Number,
    teachers_furniture_required: Number,
    eccde_furniture_available: Number,
    eccde_furniture_good: Number,
    eccde_furniture_required: Number,
    primary_furniture_available: Number,
    primary_furniture_good: Number,
    primary_furniture_required: Number,
    classroom_available: Number,
    classroom_good: Number,
    classroom_minor_repair: Number,
    classroom_major_repair: Number,
    classroom_required: Number,
    classroom_repair_description: String,
    shared_facility: String,
    shared_facility_schools: String,
    perimeter_fence: String,
    fence_condition: String,
    fence_repair_description: String,
    school_perimeter: String,
    toilet_type: String,
    toilet_cubicle_available: Number,
    toilet_minor_repair: Number,
    toilet_major_repair: Number,
    toilet_renovation_required: Number,
    toilet_additional_required: Number,
    toilet_repair_description: String,
    septic_tank: String,
    water_source: String,
    water_recommendations: String,
    electricity_source: [String],
    electricity_additional_info: String,
    waterlogged: String,
    photos: [String]
});

module.exports = mongoose.model('Silnat', SilnatSchema);
