const mongoose = require('mongoose');

const TcmatsSchema = new mongoose.Schema({
    tcmats_institution: { type: String, required: true },
    tcmats_lgea: { type: String, required: true },
    tcmats_schoolName: { type: String, required: true },
    tcmats_location: { type: String, required: true },
    tcmats_highestQualificaton: { type: String, required: true },
    tcmats_areaOfSpecialization: { type: String, required: true },
    tcmats_subjectsTaught: { type: String, required: true },
    tcmats_periodsPerWeek: { type: Number, required: true },
    tcmats_class: { type: String, required: true },
    tcmats_class_description: { type: String, required: true },
    tcmats_pupilsInClass: { type: Number, required: true },
    tcmats_gender: { type: String, required: true },
    tcmats_teaching_experience: { type: String, required: true },
    lesson_prep_1: String,
    lesson_prep_2: String,
    lesson_prep_3: String,
    lesson_prep_4: String,
    lesson_prep_5: String,
    lesson_prep_6: String,
    lesson_prep_7: String,
    lesson_prep_8: String,
    subject_mastery_1: String,
    subject_mastery_2: String,
    subject_mastery_3: String,
    subject_mastery_4: String,
    subject_mastery_5: String,
    subject_mastery_6: String,
    subject_mastery_7: String,
    subject_mastery_8: String,
    pedagogy_1: String,
    pedagogy_2: String,
    pedagogy_3: String,
    pedagogy_4: String,
    pedagogy_5: String,
    pedagogy_6: String,
    pedagogy_7: String,
    pedagogy_8: String,
    classroom_management_1: String,
    classroom_management_2: String,
    classroom_management_3: String,
    classroom_management_4: String,
    classroom_management_5: String,
    classroom_management_6: String,
    classroom_management_7: String,
    classroom_management_8: String,
    classroom_management_9: String,
    classroom_management_10: String,
    classroom_management_11: String,
    classroom_management_12: String,
    instructional_materials_1: String,
    instructional_materials_2: String,
    instructional_materials_3: String,
    instructional_materials_4: String,
    instructional_materials_5: String,
    evaluation_1: String,
    evaluation_2: String,
    evaluation_3: String,
    evaluation_4: String,
    evaluation_5: String,
    ict_1: String,
    ict_2: String,
    ict_3: String,
    ict_4: String,
    ict_5: String,
    ict_6: String,
    tcmats_difficult_topics: String
});

module.exports = mongoose.model('Tcmats', TcmatsSchema);
