const mongoose = require('mongoose');

const VoicesSchema = new mongoose.Schema({
    tcmats_institution: { type: String, required: true },
    tcmats_lgea: { type: String, required: true },
    tcmats_schoolName: { type: String, required: true },
    tcmats_location: { type: String, required: true },
    voices_class: { type: String, required: true },
    voices_class_description: { type: String, required: true },
    voices_gender: { type: String, required: true },
    voices_distance: { type: String, required: true },
    voices_difficult_topics: String,
    participation_1: String,
    participation_2: String,
    participation_3: String,
    participation_4: String,
    participation_5: String,
    participation_6: String,
    participation_7: String,
    participation_8: String,
    participation_9: String,
    participation_10: String,
    participation_11: String,
    participation_12: String,
    participation_13: String,
    participation_14: String,
    participation_15: String,
    school_building: String,
    furniture: String,
    classroom_condition: [String],
    perimeter_fence: String,
    fence_state: String,
    toilet_type: String,
    toilet_cubicles_available: Number,
    toilet_cubicles_minor_repair: Number,
    toilet_cubicles_major_repair: Number,
    toilet_cubicles_additional: Number,
    septic_tank: String,
    water_source: String,
    electricity_source: [String],
    clubs: [String],
    clubs_frequency: String,
    sports_equipment: [String],
    waterlogged: String,
    major_requests: String
});

module.exports = mongoose.model('Voices', VoicesSchema);
